config/routes.rb
Rails.application.routes.draw do

  resources :sku_mappings
  resources :sku_patterns

  resources :imports, :only => [:index, :show, :new, :create]

  resources :states

  resources :mws_messages, :only => [:show]

  resources :stores do
    post 'sync', :on => :member
    post 'queue', :on => :member
  end

  resources :vendors do
  	get 'by_name', :on => :collection
  end
  resources :brands do
  	get 'by_name', :on => :collection
  end
  resources :products do
  	get 'by_sku_and_brand_id', :on => :collection
  end

  resources :listings # TODO only index?

  resources :variants, :variant_images do
  	get 'by_sku', :on => :collection
  end

  resources :sub_variants do
  	get 'by_sku', :on => :collection
  end

  resources :mws_requests, :only => [:show, :index]
  resources :mws_orders do #, :only => [:show, :index, :update] do
  	collection do
  		get "export_to_csv"
  	end
  end
  resources :mws_order_items, :only => [:show]
  resources :analytics, :only => [:index]

  root :to                   => 'home#index'

end

app/models/mws_order.rb
class MwsOrder < ActiveRecord::Base
	belongs_to :mws_response
	belongs_to :store
	has_many :mws_order_items, :dependent => :destroy
	has_many :omx_requests
	has_many :omx_responses, :through => :omx_requests
	validates_uniqueness_of :amazon_order_id
	validates_presence_of :mws_response_id
	validates_presence_of :purchase_date
	validates_associated :store
	default_scope ->{ order( 'purchase_date DESC' ) }

	MAX_ORDER_ITEM_PAGES = 20
	MAX_FAILURE_COUNT = 1
	ORDER_ITEM_FAIL_WAIT = 60

	# return a list of skus that, as yet, have not been matched up to products, variants, or sub_variants
	def self.get_unmatched_skus
		where(:id => MwsOrderItem.get_unmatched_skus)
	end

	def self.search(search)
		# get sub_matches from order_items
		o1 = MwsOrderItem.search(search)

		# get direct matches at order level
		fields = [ 'amazon_order_id', 'seller_order_id', 'address_line_1', 'address_line_2', 'address_line_3', 'city', 'state_or_region', 'country_code', 'postal_code', 'buyer_name', 'buyer_email', 'shipment_service_level_category', 'name']
		bind_vars = MwsHelper::search_helper(fields, search)
		o2 = select('id').where(bind_vars).collect { |o| o.id }

		# combine the two arrays of IDs and remove duplicates, and return all relevant records
		where(:id => o1 | o2)
	end

	# return a value between 0 and 6 for the number of seconds to delay between OrderItem requests to Amazon
	def self.get_sleep_time_per_order(order_count)
		if order_count.is_a?(Numeric) && order_count>0
			sleep_time = 0.0
			request_buffer = 15.0
			refresh_interval = 5.0
			sleep_time = (([order_count - request_buffer, 0.0].max) / order_count)*refresh_interval
			return sleep_time
		else
			return 0
		end
	end

  # set each item in an order to shipped
	def set_shipped
		self.mws_order_items.each do |i|
			i.set_shipped
		end
	end

	def get_item_quantity_ordered
		q = 0
		q += self.number_of_items_unshipped ? self.number_of_items_unshipped : 0
		q += self.number_of_items_shipped ? self.number_of_items_shipped : 0
		return q
	end

	def get_item_quantity_loaded
		q = 0
		self.mws_order_items.each do |i|
			q += i.quantity_ordered
		end
		return q
	end

	def get_item_quantity_missing
		return get_item_quantity_ordered - get_item_quantity_loaded
	end

	def get_item_price
		total = 0
		self.mws_order_items.each do |i|
			total += i.get_item_price
		end
		return total
	end

	def get_ship_price
		total = 0
		self.mws_order_items.each do |i|
			total += i.get_ship_price
		end
		return total
	end

	def get_gift_price
		total = 0
		self.mws_order_items.each do |i|
			total += i.get_gift_price
		end
		return total
	end

	def get_total_price
		total = 0
		self.mws_order_items.each do |i|
			total += i.get_total_price
		end
		return total
	end

	def pushed_to_omx?
		pushed = "Error"
		if self.fulfillment_channel == "AFN"
			return 'N/A'
		elsif (self.order_status != 'Unshipped' && self.order_status != 'PartiallyShipped')
			return 'Shipped'
		end
		self.omx_responses.each do |resp|
			if !resp.ordermotion_order_number.nil? && resp.ordermotion_order_number != ''
				pushed = 'Yes'
			elsif resp.error_data.nil? || resp.error_data == ''
				pushed = 'No'
			elsif !resp.error_data.match(/The provided Order ID has already been used for the provided store/).nil?
				pushed = 'Dup'
			end
		end
		return pushed
	end

	def reprocess_order
		store = self.store
		if !store.mws_connection.nil?
			return process_order(store.mws_connection)
		end
	end

	# Process XML order into ActiveRecord, and process items on order
	def process_order(mws_connection)
	  #puts "      PROCESS_ORDER: #{self.amazon_order_id}"
		return_code = fetch_order_items(mws_connection)

		#TODO if reprocessing, use the update OMX API call rather than append
		if get_item_quantity_missing == 0 && self.fulfillment_channel == "MFN" && (self.order_status == 'Unshipped' || self.order_status == 'PartiallyShipped')
		  #puts "      PROCESS_ORDER: about to append to omx"
			#append_to_omx
		else
		  #puts "      PROCESS_ORDER: not appending to omx, return code #{return_code}"
		end
		return return_code
	end

	# fetch items associated with this order
	# calls the Amazon MWS API
	def fetch_order_items(mws_connection)
	  #puts "        FETCH_ORDER_ITEMS: for order #{self.amazon_order_id}, about to call MWS ListOrderItems"
		parent_request = self.mws_response.mws_request
		request = MwsRequest.create!(:request_type => "ListOrderItems", :store_id => parent_request.store_id, :mws_request_id => parent_request.id)
		response = mws_connection.get_list_order_items(:amazon_order_id => self.amazon_order_id)
		#puts "        FETCH_ORDER_ITEMS: called MWS ListOrderItems, about to process response"
		next_token = request.process_response(mws_connection, response,0,0)
		#puts "        FETCH_ORDER_ITEMS: back, finished process_response"
		if next_token.is_a?(Numeric)
			return next_token
		end

		page_num = 1
		failure_count = 0
		while next_token.is_a?(String) && page_num<MAX_ORDER_ITEM_PAGES do
		  #puts "        FETCH_ORDER_ITEMS: next_token is present, about to fetch by next token for #{self.amazon_order_id}"
			response = mws_connection.get_list_order_items_by_next_token(:next_token => next_token)
			#puts "        FETCH_ORDER_ITEMS: called MWS ListOrderItemsByNextToken, about to process response"
			n = request.process_response(mws_connection,response,page_num,ORDER_ITEM_FAIL_WAIT)
			if n.is_a?(Numeric)
				failure_count += 1
				if failure_count >= MAX_FAILURE_COUNT
					return n
				end
			else
				page_num += 1 # don't want to increment page if there is an error
				next_token = n
			end
			#puts "        FETCH_ORDER_ITEMS: finished process_response for next token"
		end
		#puts "        FETCH_ORDER_ITEMS: finishing order #{self.amazon_order_id}"
	end

	def process_order_item(item, response_id)
	  #puts "              PROCESS_ORDER_ITEM: order #{self.amazon_order_id}, item #{item.amazon_order_item_id}"

		amz_item = MwsOrderItem.find_by_amazon_order_item_id(item.amazon_order_item_id)
		if amz_item.nil?
		  amz_item = MwsOrderItem.create(:amazon_order_item_id=>item.amazon_order_item_id, :seller_sku=>item.seller_sku, :mws_response_id=>response_id, :mws_order_id=>self.id, :amazon_order_id=>self.amazon_order_id)
		  #puts "              PROCESS_ORDER_ITEM: new item #{amz_item.amazon_order_item_id} created, id: #{amz_item.id}"
		else
		  #puts "              PROCESS_ORDER_ITEM: existing item #{amz_item.amazon_order_item_id} updated, id: #{amz_item.id}"
		end
		amz_item.update_attributes(item.attributes)
		#puts "              PROCESS_ORDER_ITEM: finished"
	end


end

app/controllers/mws_orders_controller.rb
class MwsOrdersController < ApplicationController
  before_action :set_mws_order, only: [:show, :edit, :update, :destroy]

  # GET /mws_orders
  # GET /mws_orders.json
  def index
    @mws_orders = MwsOrder.all
  end

  # GET /mws_orders/1
  # GET /mws_orders/1.json
  def show
  end

  # GET /mws_orders/new
  def new
    @mws_order = MwsOrder.new
  end

  # GET /mws_orders/1/edit
  def edit
  end

  # POST /mws_orders
  # POST /mws_orders.json
  def create
    @mws_order = MwsOrder.new(mws_order_params)

    respond_to do |format|
      if @mws_order.save
        format.html { redirect_to @mws_order, notice: 'Mws order was successfully created.' }
        format.json { render :show, status: :created, location: @mws_order }
      else
        format.html { render :new }
        format.json { render json: @mws_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mws_orders/1
  # PATCH/PUT /mws_orders/1.json
  def update
    respond_to do |format|
      if @mws_order.update(mws_order_params)
        format.html { redirect_to @mws_order, notice: 'Mws order was successfully updated.' }
        format.json { render :show, status: :ok, location: @mws_order }
      else
        format.html { render :edit }
        format.json { render json: @mws_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mws_orders/1
  # DELETE /mws_orders/1.json
  def destroy
    @mws_order.destroy
    respond_to do |format|
      format.html { redirect_to mws_orders_url, notice: 'Mws order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mws_order
      @mws_order = MwsOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mws_order_params
      params.require(:mws_order).permit(:amazon_order_id, :seller_order_id, :purchase_date, :last_update_date, :order_status, :fulfillment_channel, :sales_channel, :order_channel, :ship_service_level, :amount, :currency_code, :address_line_1, :address_line_2, :address_line_3, :city, :county, :district, :state_or_region, :postal_code, :country_code, :phone, :number_of_items_shipped, :number_of_items_unshipped, :marketplace_id, :buyer_name, :buyer_email, :ship_service_level_category, :mws_response_id)
    end
end

app/helpers/mws_orders_helper.rb
module MwsOrdersHelper
end

app/views/mws_orders/_form.html.erb
<%= simple_form_for(@mws_order) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :amazon_order_id %>
    <%= f.input :seller_order_id %>
    <%= f.input :purchase_date %>
    <%= f.input :last_update_date %>
    <%= f.input :order_status %>
    <%= f.input :fulfillment_channel %>
    <%= f.input :sales_channel %>
    <%= f.input :order_channel %>
    <%= f.input :ship_service_level %>
    <%= f.input :amount %>
    <%= f.input :currency_code %>
    <%= f.input :address_line_1 %>
    <%= f.input :address_line_2 %>
    <%= f.input :address_line_3 %>
    <%= f.input :city %>
    <%= f.input :county %>
    <%= f.input :district %>
    <%= f.input :state_or_region %>
    <%= f.input :postal_code %>
    <%= f.input :country_code %>
    <%= f.input :phone %>
    <%= f.input :number_of_items_shipped %>
    <%= f.input :number_of_items_unshipped %>
    <%= f.input :marketplace_id %>
    <%= f.input :buyer_name %>
    <%= f.input :buyer_email %>
    <%= f.input :ship_service_level_category %>
    <%= f.input :mws_response_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/mws_orders/edit.html.erb
<div class="page-header">
  <%= link_to mws_orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @mws_order, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing mws_order</h1>
</div>

<%= render 'form' %>

app/views/mws_orders/index.html.erb
<div class="page-header">
  <%= link_to new_mws_order_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Mws order
  <% end %>
  <h1>Listing mws_orders</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Amazon order</th>
            <th>Seller order</th>
            <th>Purchase date</th>
            <th>Last update date</th>
            <th>Order status</th>
            <th>Fulfillment channel</th>
            <th>Sales channel</th>
            <th>Order channel</th>
            <th>Ship service level</th>
            <th>Amount</th>
            <th>Currency code</th>
            <th>Address line 1</th>
            <th>Address line 2</th>
            <th>Address line 3</th>
            <th>City</th>
            <th>County</th>
            <th>District</th>
            <th>State or region</th>
            <th>Postal code</th>
            <th>Country code</th>
            <th>Phone</th>
            <th>Number of items shipped</th>
            <th>Number of items unshipped</th>
            <th>Marketplace</th>
            <th>Buyer name</th>
            <th>Buyer email</th>
            <th>Ship service level category</th>
            <th>Mws response</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @mws_orders) do |mws_order| %>
            <td><%= mws_order.amazon_order_id %></td>
            <td><%= mws_order.seller_order_id %></td>
            <td><%= mws_order.purchase_date %></td>
            <td><%= mws_order.last_update_date %></td>
            <td><%= mws_order.order_status %></td>
            <td><%= mws_order.fulfillment_channel %></td>
            <td><%= mws_order.sales_channel %></td>
            <td><%= mws_order.order_channel %></td>
            <td><%= mws_order.ship_service_level %></td>
            <td><%= mws_order.amount %></td>
            <td><%= mws_order.currency_code %></td>
            <td><%= mws_order.address_line_1 %></td>
            <td><%= mws_order.address_line_2 %></td>
            <td><%= mws_order.address_line_3 %></td>
            <td><%= mws_order.city %></td>
            <td><%= mws_order.county %></td>
            <td><%= mws_order.district %></td>
            <td><%= mws_order.state_or_region %></td>
            <td><%= mws_order.postal_code %></td>
            <td><%= mws_order.country_code %></td>
            <td><%= mws_order.phone %></td>
            <td><%= mws_order.number_of_items_shipped %></td>
            <td><%= mws_order.number_of_items_unshipped %></td>
            <td><%= mws_order.marketplace_id %></td>
            <td><%= mws_order.buyer_name %></td>
            <td><%= mws_order.buyer_email %></td>
            <td><%= mws_order.ship_service_level_category %></td>
            <td><%= mws_order.mws_response_id %></td>
            <td><%= link_to 'Show', mws_order %></td>
        <td><%= link_to 'Edit', edit_mws_order_path(mws_order) %></td>
        <td><%= link_to 'Destroy', mws_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/mws_orders/new.html.erb
<div class="page-header">
  <%= link_to mws_orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New mws_order</h1>
</div>

<%= render 'form' %>

app/views/mws_orders/show.html.erb
<div class="page-header">
  <%= link_to mws_orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_mws_order_path(@mws_order), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show mws_order</h1>
</div>

<dl class="dl-horizontal">
  <dt>Amazon order:</dt>
  <dd><%= @mws_order.amazon_order_id %></dd>

  <dt>Seller order:</dt>
  <dd><%= @mws_order.seller_order_id %></dd>

  <dt>Purchase date:</dt>
  <dd><%= @mws_order.purchase_date %></dd>

  <dt>Last update date:</dt>
  <dd><%= @mws_order.last_update_date %></dd>

  <dt>Order status:</dt>
  <dd><%= @mws_order.order_status %></dd>

  <dt>Fulfillment channel:</dt>
  <dd><%= @mws_order.fulfillment_channel %></dd>

  <dt>Sales channel:</dt>
  <dd><%= @mws_order.sales_channel %></dd>

  <dt>Order channel:</dt>
  <dd><%= @mws_order.order_channel %></dd>

  <dt>Ship service level:</dt>
  <dd><%= @mws_order.ship_service_level %></dd>

  <dt>Amount:</dt>
  <dd><%= @mws_order.amount %></dd>

  <dt>Currency code:</dt>
  <dd><%= @mws_order.currency_code %></dd>

  <dt>Address line 1:</dt>
  <dd><%= @mws_order.address_line_1 %></dd>

  <dt>Address line 2:</dt>
  <dd><%= @mws_order.address_line_2 %></dd>

  <dt>Address line 3:</dt>
  <dd><%= @mws_order.address_line_3 %></dd>

  <dt>City:</dt>
  <dd><%= @mws_order.city %></dd>

  <dt>County:</dt>
  <dd><%= @mws_order.county %></dd>

  <dt>District:</dt>
  <dd><%= @mws_order.district %></dd>

  <dt>State or region:</dt>
  <dd><%= @mws_order.state_or_region %></dd>

  <dt>Postal code:</dt>
  <dd><%= @mws_order.postal_code %></dd>

  <dt>Country code:</dt>
  <dd><%= @mws_order.country_code %></dd>

  <dt>Phone:</dt>
  <dd><%= @mws_order.phone %></dd>

  <dt>Number of items shipped:</dt>
  <dd><%= @mws_order.number_of_items_shipped %></dd>

  <dt>Number of items unshipped:</dt>
  <dd><%= @mws_order.number_of_items_unshipped %></dd>

  <dt>Marketplace:</dt>
  <dd><%= @mws_order.marketplace_id %></dd>

  <dt>Buyer name:</dt>
  <dd><%= @mws_order.buyer_name %></dd>

  <dt>Buyer email:</dt>
  <dd><%= @mws_order.buyer_email %></dd>

  <dt>Ship service level category:</dt>
  <dd><%= @mws_order.ship_service_level_category %></dd>

  <dt>Mws response:</dt>
  <dd><%= @mws_order.mws_response_id %></dd>

</dl>