config/routes.rb
Rails.application.routes.draw do

  resources :sku_mappings
  resources :sku_patterns

  resources :imports, :only => [:index, :show, :new, :create]

  resources :states

  resources :mws_messages, :only => [:show]

  resources :stores do
    post 'sync', :on => :member
    post 'queue', :on => :member
  end

  resources :vendors do
  	get 'by_name', :on => :collection
  end
  resources :brands do
  	get 'by_name', :on => :collection
  end
  resources :products do
  	get 'by_sku_and_brand_id', :on => :collection
  end

  resources :listings # TODO only index?

  resources :variants, :variant_images do
  	get 'by_sku', :on => :collection
  end

  resources :sub_variants do
  	get 'by_sku', :on => :collection
  end

  resources :mws_requests, :only => [:show, :index]
  resources :mws_orders do #, :only => [:show, :index, :update] do
  	collection do
  		get "export_to_csv"
  	end
  end
  resources :mws_order_items, :only => [:show]
  resources :analytics, :only => [:index]

  root :to                   => 'home#index'

end

app/models/mws_order_item.rb
class MwsOrderItem < ActiveRecord::Base
	belongs_to :mws_order
	belongs_to :mws_response
	belongs_to :product
	belongs_to :variant
	belongs_to :sub_variant
	
	validates_uniqueness_of :amazon_order_item_id
	validates_presence_of :mws_order_id
	validates_presence_of :clean_sku
	validates :item_price, :item_tax, :promotion_discount, :shipping_price, :shipping_tax, :shipping_discount, :gift_price, :gift_tax, :numericality => { :only_integer => false, :greater_than_or_equal_to => 0 }
	validates :quantity_ordered, :quantity_shipped, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 }

	before_validation :save_clean_sku, :zero_missing_numbers
	before_save :save_catalog_match

	# searches order items BUT returns an ActiveRecord association of the mws_orders associated with the matched mws_order_items
	def self.search(search)
		fields = [ 'asin', 'clean_sku', 'title'] 
		select("mws_order_id").where(MwsHelper::search_helper(fields, search)).group('mws_order_id').collect { |oi| oi.mws_order_id }
	end
		
	def set_shipped
		self.quantity_shipped = self.quantity_ordered
		self.save
	end

	def is_gift?
		if !self.gift_message_text.nil? || !self.gift_wrap_level.nil? 
			return 1
		else
			return 0
		end
	end
	
	# Return the price per unit including tax, net of promotion discounts
	def get_item_price_per_unit
		if self.quantity_ordered.nil? || self.quantity_ordered == 0
			return 0
		else
			return self.get_item_price / self.quantity_ordered
		end
	end

	def get_item_price
		total = 0
		total += self.item_price ? self.item_price : 0 
		total += self.item_tax ? self.item_tax : 0
		total -= self.promotion_discount ? self.promotion_discount : 0
		return total
	end

	def get_ship_price
		total = 0
		total += self.shipping_price ? self.shipping_price : 0
		total += self.shipping_tax ? self.shipping_tax : 0
		total -= self.shipping_discount ? self.shipping_discount : 0
		return total
	end

	def get_gift_price
		total = 0
		total += self.gift_price ? self.gift_price : 0
		total += self.gift_tax ? self.gift_tax : 0
		return total
	end
	
	def get_total_price
		total = self.get_item_price + self.get_ship_price + self.get_gift_price
		return total
	end

	def get_price_subtotal
		total = 0
		total += self.item_price ? self.item_price : 0
		total += self.shipping_price ? self.shipping_price : 0
		total += self.gift_price ? self.gift_price : 0
		return total
	end

	def get_discount_subtotal
		total = 0
		total += self.promotion_discount ? self.promotion_discount : 0
		total += self.shipping_discount ? self.shipping_discount : 0
		return total
	end

	def get_tax_subtotal
		total = 0
		total += self.item_tax ? self.item_tax : 0
		total += self.shipping_tax ? self.shipping_tax : 0
		total += self.gift_tax ? self.gift_tax : 0
		return total		
	end
	
#	def get_omx_info
#		omx_connection = RubyOmx::Base.new(
#			"http_biz_id" => 'KbmCrvnukGKUosDSTVhWbhrYBlggjNYxGqsujuglguAJhXeKBYDdpwyiRcywvmiUrpHilblPqKgiPAOIfxOfvFOmZLUiNuIfeDrKJxvjeeblkhphUhgPixbvaCJADgIfaDjHWFHXePIFchOjQciNRdrephpJFEfGoUaSFAOcjHmhfgZidlmUsCBdXgmmxIBKhgRjxjJaTcrnCgSkghRWvRwjZgVeVvhHqALceQpdJLphwDlfFXgIHYjCGjCiwZW',
#			"udi_auth_token" => '7509fd470db4004809083c0048ef983102d6325b27730421704c1b0899109ab51de58e4dfd80acff062f8042360b5ae01ed4851f50a5d5fe38a10e81c0471a089f20799ddf11c81cc541a10a014fe04e190aee6049efdf97699096bd79db0a9fd04ca90b2a90f63925c223d236fbe97b047c104b900b7e1010fbb39453e0920'
#		)
#		response = omx_connection.get_item_info(:raw_xml => 0, :item_code => self.clean_sku)
#		return response
#	end	

	def self.get_unmatched_skus
		MwsOrderItem.select("mws_order_id").where(:product_id=>nil).group('mws_order_id')
	end

	def self.refresh_all_sku_mappings
		MwsOrderItem.all.each do |oi|
			oi.save
		end
	end

	# returns either a product, variant, or sub_variant depending on what is available
	protected
	def save_catalog_match
		x = get_catalog_match
		if x.class.to_s == 'Product'
			self.product_id = x.id
		elsif x.class.to_s == 'Variant'
			self.variant_id = x.id
			self.product_id = x.product.id
		elsif x.class.to_s == 'SubVariant'
			self.sub_variant_id = x.id
			self.variant_id = x.variant.id
			self.product_id = x.product.id
		end
	end

	def get_catalog_match
		x = SubVariant.find_by_sku(self.clean_sku)
		return x if !x.nil?
		x = Variant.find_by_sku(self.clean_sku)
		return x if !x.nil?
		x = Product.find_by_sku(self.clean_sku)
		return x if !x.nil?
		return SkuMapping.get_catalog_match(self.clean_sku)
	end

	def save_clean_sku
		if !self.seller_sku.nil?
			self.clean_sku = SkuPattern.strip_amazon_suffix(self.seller_sku)
		end
	end

	def zero_missing_numbers
		numbers = [:item_price, :item_tax, :promotion_discount, :shipping_price, :shipping_tax, :shipping_discount, :gift_price, :gift_tax, :quantity_ordered, :quantity_shipped]
		numbers.each do |n|
			if self[n].nil?
				self[n] = 0
			end
		end
	end
	
end

app/controllers/mws_order_items_controller.rb
class MwsOrderItemsController < ApplicationController
  before_action :set_mws_order_item, only: [:show, :edit, :update, :destroy]

  # GET /mws_order_items
  # GET /mws_order_items.json
  def index
    @mws_order_items = MwsOrderItem.all
  end

  # GET /mws_order_items/1
  # GET /mws_order_items/1.json
  def show
  end

  # GET /mws_order_items/new
  def new
    @mws_order_item = MwsOrderItem.new
  end

  # GET /mws_order_items/1/edit
  def edit
  end

  # POST /mws_order_items
  # POST /mws_order_items.json
  def create
    @mws_order_item = MwsOrderItem.new(mws_order_item_params)

    respond_to do |format|
      if @mws_order_item.save
        format.html { redirect_to @mws_order_item, notice: 'Mws order item was successfully created.' }
        format.json { render :show, status: :created, location: @mws_order_item }
      else
        format.html { render :new }
        format.json { render json: @mws_order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mws_order_items/1
  # PATCH/PUT /mws_order_items/1.json
  def update
    respond_to do |format|
      if @mws_order_item.update(mws_order_item_params)
        format.html { redirect_to @mws_order_item, notice: 'Mws order item was successfully updated.' }
        format.json { render :show, status: :ok, location: @mws_order_item }
      else
        format.html { render :edit }
        format.json { render json: @mws_order_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mws_order_items/1
  # DELETE /mws_order_items/1.json
  def destroy
    @mws_order_item.destroy
    respond_to do |format|
      format.html { redirect_to mws_order_items_url, notice: 'Mws order item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mws_order_item
      @mws_order_item = MwsOrderItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mws_order_item_params
      params.require(:mws_order_item).permit(:asin, :amazon_order_item_id, :seller_sku, :title, :quantity_ordered, :quantity_shipped, :item_price, :item_price_currency, :shipping_price, :shipping_price_currency, :gift_price, :gift_price_currency, :item_tax, :item_tax_currency, :shipping_tax, :shipping_tax_currency, :gift_tax, :gift_tax_currency, :shipping_discount, :shipping_discount_currency, :promotion_discount, :promotion_discount_currency, :gift_wrap_level, :gift_message_text, :mws_order_id, :amazon_order_id)
    end
end

app/helpers/mws_order_items_helper.rb
module MwsOrderItemsHelper
end

app/views/mws_order_items/_form.html.erb
<%= simple_form_for(@mws_order_item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :asin %>
    <%= f.input :amazon_order_item_id %>
    <%= f.input :seller_sku %>
    <%= f.input :title %>
    <%= f.input :quantity_ordered %>
    <%= f.input :quantity_shipped %>
    <%= f.input :item_price %>
    <%= f.input :item_price_currency %>
    <%= f.input :shipping_price %>
    <%= f.input :shipping_price_currency %>
    <%= f.input :gift_price %>
    <%= f.input :gift_price_currency %>
    <%= f.input :item_tax %>
    <%= f.input :item_tax_currency %>
    <%= f.input :shipping_tax %>
    <%= f.input :shipping_tax_currency %>
    <%= f.input :gift_tax %>
    <%= f.input :gift_tax_currency %>
    <%= f.input :shipping_discount %>
    <%= f.input :shipping_discount_currency %>
    <%= f.input :promotion_discount %>
    <%= f.input :promotion_discount_currency %>
    <%= f.input :gift_wrap_level %>
    <%= f.input :gift_message_text %>
    <%= f.input :mws_order_id %>
    <%= f.input :amazon_order_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/mws_order_items/edit.html.erb
<div class="page-header">
  <%= link_to mws_order_items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @mws_order_item, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing mws_order_item</h1>
</div>

<%= render 'form' %>

app/views/mws_order_items/index.html.erb
<div class="page-header">
  <%= link_to new_mws_order_item_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Mws order item
  <% end %>
  <h1>Listing mws_order_items</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Asin</th>
            <th>Amazon order item</th>
            <th>Seller sku</th>
            <th>Title</th>
            <th>Quantity ordered</th>
            <th>Quantity shipped</th>
            <th>Item price</th>
            <th>Item price currency</th>
            <th>Shipping price</th>
            <th>Shipping price currency</th>
            <th>Gift price</th>
            <th>Gift price currency</th>
            <th>Item tax</th>
            <th>Item tax currency</th>
            <th>Shipping tax</th>
            <th>Shipping tax currency</th>
            <th>Gift tax</th>
            <th>Gift tax currency</th>
            <th>Shipping discount</th>
            <th>Shipping discount currency</th>
            <th>Promotion discount</th>
            <th>Promotion discount currency</th>
            <th>Gift wrap level</th>
            <th>Gift message text</th>
            <th>Mws order</th>
            <th>Amazon order</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @mws_order_items) do |mws_order_item| %>
            <td><%= mws_order_item.asin %></td>
            <td><%= mws_order_item.amazon_order_item_id %></td>
            <td><%= mws_order_item.seller_sku %></td>
            <td><%= mws_order_item.title %></td>
            <td><%= mws_order_item.quantity_ordered %></td>
            <td><%= mws_order_item.quantity_shipped %></td>
            <td><%= mws_order_item.item_price %></td>
            <td><%= mws_order_item.item_price_currency %></td>
            <td><%= mws_order_item.shipping_price %></td>
            <td><%= mws_order_item.shipping_price_currency %></td>
            <td><%= mws_order_item.gift_price %></td>
            <td><%= mws_order_item.gift_price_currency %></td>
            <td><%= mws_order_item.item_tax %></td>
            <td><%= mws_order_item.item_tax_currency %></td>
            <td><%= mws_order_item.shipping_tax %></td>
            <td><%= mws_order_item.shipping_tax_currency %></td>
            <td><%= mws_order_item.gift_tax %></td>
            <td><%= mws_order_item.gift_tax_currency %></td>
            <td><%= mws_order_item.shipping_discount %></td>
            <td><%= mws_order_item.shipping_discount_currency %></td>
            <td><%= mws_order_item.promotion_discount %></td>
            <td><%= mws_order_item.promotion_discount_currency %></td>
            <td><%= mws_order_item.gift_wrap_level %></td>
            <td><%= mws_order_item.gift_message_text %></td>
            <td><%= mws_order_item.mws_order_id %></td>
            <td><%= mws_order_item.amazon_order_id %></td>
            <td><%= link_to 'Show', mws_order_item %></td>
        <td><%= link_to 'Edit', edit_mws_order_item_path(mws_order_item) %></td>
        <td><%= link_to 'Destroy', mws_order_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/mws_order_items/new.html.erb
<div class="page-header">
  <%= link_to mws_order_items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New mws_order_item</h1>
</div>

<%= render 'form' %>

app/views/mws_order_items/show.html.erb
<div class="page-header">
  <%= link_to mws_order_items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_mws_order_item_path(@mws_order_item), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show mws_order_item</h1>
</div>

<dl class="dl-horizontal">
  <dt>Asin:</dt>
  <dd><%= @mws_order_item.asin %></dd>

  <dt>Amazon order item:</dt>
  <dd><%= @mws_order_item.amazon_order_item_id %></dd>

  <dt>Seller sku:</dt>
  <dd><%= @mws_order_item.seller_sku %></dd>

  <dt>Title:</dt>
  <dd><%= @mws_order_item.title %></dd>

  <dt>Quantity ordered:</dt>
  <dd><%= @mws_order_item.quantity_ordered %></dd>

  <dt>Quantity shipped:</dt>
  <dd><%= @mws_order_item.quantity_shipped %></dd>

  <dt>Item price:</dt>
  <dd><%= @mws_order_item.item_price %></dd>

  <dt>Item price currency:</dt>
  <dd><%= @mws_order_item.item_price_currency %></dd>

  <dt>Shipping price:</dt>
  <dd><%= @mws_order_item.shipping_price %></dd>

  <dt>Shipping price currency:</dt>
  <dd><%= @mws_order_item.shipping_price_currency %></dd>

  <dt>Gift price:</dt>
  <dd><%= @mws_order_item.gift_price %></dd>

  <dt>Gift price currency:</dt>
  <dd><%= @mws_order_item.gift_price_currency %></dd>

  <dt>Item tax:</dt>
  <dd><%= @mws_order_item.item_tax %></dd>

  <dt>Item tax currency:</dt>
  <dd><%= @mws_order_item.item_tax_currency %></dd>

  <dt>Shipping tax:</dt>
  <dd><%= @mws_order_item.shipping_tax %></dd>

  <dt>Shipping tax currency:</dt>
  <dd><%= @mws_order_item.shipping_tax_currency %></dd>

  <dt>Gift tax:</dt>
  <dd><%= @mws_order_item.gift_tax %></dd>

  <dt>Gift tax currency:</dt>
  <dd><%= @mws_order_item.gift_tax_currency %></dd>

  <dt>Shipping discount:</dt>
  <dd><%= @mws_order_item.shipping_discount %></dd>

  <dt>Shipping discount currency:</dt>
  <dd><%= @mws_order_item.shipping_discount_currency %></dd>

  <dt>Promotion discount:</dt>
  <dd><%= @mws_order_item.promotion_discount %></dd>

  <dt>Promotion discount currency:</dt>
  <dd><%= @mws_order_item.promotion_discount_currency %></dd>

  <dt>Gift wrap level:</dt>
  <dd><%= @mws_order_item.gift_wrap_level %></dd>

  <dt>Gift message text:</dt>
  <dd><%= @mws_order_item.gift_message_text %></dd>

  <dt>Mws order:</dt>
  <dd><%= @mws_order_item.mws_order_id %></dd>

  <dt>Amazon order:</dt>
  <dd><%= @mws_order_item.amazon_order_id %></dd>

</dl>